### ISSUE TITLE
Calling file['entity'] raises "AlignmentError"

### ISSUE THREAD

**Issue by hbredin** [PaulLerner/pyannote-db-plumcot#23]
How to reproduce?

```python
from pyannote.database import get_protocol
protocol = get_protocol('TheBigBangTheory.SpeakerDiarization.0')
test_file = next(protocol.test())
test_file['entity']
# AlignmentError: [...] are different texts.
```

Is this a known issue? 
Is this related to your suggested changes in https://github.com/PaulLerner/pyannote-db-plumcot/issues/13?

**Comment by PaulLerner** [comment]
Nope, works fine for me (just tested)
This has got something to do with the alignment (using `spacy.gold.align`) done in https://github.com/PaulLerner/pyannote-db-plumcot/blob/video/Plumcot/loader/loader.py#L179
What version of spacy are you using ?

**Comment by hbredin** [comment]
This is indeed an issue with `spacy` version.

Works with 2.2.4, not with 2.3.2.

However, prodigy 1.10.4 requires spacy<2.4.0,>=2.3.0

**Comment by hbredin** [comment]
Does any of [this](https://spacy.io/usage/v2-3#migrating) make it obvious what needs to be changed to support spacy >=2.3?

**Comment by PaulLerner** [comment]
Ok, I don't know why there's an `AlignmentError` though, since text from forced-alignment and entities are almost identical...

**Comment by PaulLerner** [comment]
> Does any of [this](https://spacy.io/usage/v2-3#migrating) make it obvious what needs to be changed to support spacy >=2.3?

No since this describes changes with the tokenizer but both forced-alignment and entities text are already tokenized.
`gold.align` works directly on tokens using Levenshtein distance https://spacy.io/api/goldparse#align

**Comment by PaulLerner** [comment]
Note that until we figure this out, you can use the `EL` protocols to have access to entities annotation (without forced-alignment timing), e.g. `TheBigBangTheory.SpeakerDiarization.EL`
